languageCode = "en-us"
title = "MongoDB Tutorials"
theme = "mongodb-tutorials"
pygmentsuseclasses = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"

sourceContentDir = "content"
contentDir = "content-html"

[taxonomies]
  category = ""
  tags = ""

[tags]

  # Language Options
  [tags.shell]
  name = "Mongo Shell"
  facet = "language"
  
  [tags.python]
  name = "Python"
  facet = "language"
  
  [tags.ruby]
  name = "Ruby"
  facet = "language"
  
  # Product Options
  [tags.mongodb]
  name = "MongoDB"
  facet = "product"
  
  [tags.mongodb-enterprise]
  name = "MongoDB Enterprise"
  facet = "product"
  
  [tags.bi]
  name = "BI Connector"
  facet = "product"
  
  [tags.compass]
  name = "Compass"
  facet = "product"
  
  [tags.driver]
  name = "Driver"
  facet = "product"
  
  # Topic Options
  [tags.administration]
  name = "Administration"
  facet = "topic"
  
  [tags.crud]
  name = "CRUD"
  facet = "topic"
  
  [tags.performance]
  name = "Performance"
  facet = "topic"
  
  [tags.replication]
  name = "Replication"
  facet = "topic"
  
  [tags.security]
  name = "Security"
  facet = "topic"
  
  [tags.sharding]
  name = "Sharding"
  facet = "topic"
  
  # Level Options
  [tags.beginner]
  name = "Beginner"
  facet = "level"
  
  [tags.intermediate]
  name = "Intermediate"
  facet = "level"
  
  [tags.advanced]
  name = "Advanced"
  facet = "level"
