baseurl = "http://example.org/"
languageCode = "en-us"
title = "MongoDB Tutorials"
theme = "mongodb-tutorials"

[taxonomies]
  category = "" 
  tags = ""

[tags]
  shell = "language"
  python = "language"
  ruby = "language"
  compass = "product"
  bi = "product"
  mongodb = "product"
  driver = "product"
  beginner = "level"
  crud = "topic"
