baseurl = "http://docs-mongodb-org-staging.s3-website-us-east-1.amazonaws.com/tutorials/kirby/master"
languageCode = "en-us"
title = "MongoDB Tutorials"
theme = "mongodb-tutorials"
pygmentsuseclasses = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[taxonomies]
  category = "" 
  tags = ""

[tags]
  shell = "language"
  python = "language"
  ruby = "language"
  compass = "product"
  bi = "product"
  mongodb = "product"
  driver = "product"
  beginner = "level"
  crud = "topic"
